matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script: ./gradlew test

    - language: node_js
      node_js: "7"
      before_script:
        - cd web
        - npm install
      script: npm test

